import { precacheAndRoute } from "workbox-precaching";
import { localDB } from "../lib/db.js";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate, CacheFirst } from "workbox-strategies";
import { CacheableResponsePlugin } from "workbox-cacheable-response";

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

registerRoute(
  ({ url }) =>
    url.origin === "https://cdn.tiny.cloud" ||
    url.origin === "https://sp.tinymce.com",
  new StaleWhileRevalidate({
    cacheName: "tinymce-assets",
  }),
);

// Offline code runner: compilers (/toolchains/*) and the engine's own
// Workers/wasm (/assets/*) are downloaded the first time a language is used,
// then served from this cache forever - their file names contain a version
// or content hash, so a cached copy can never be stale. This is what lets
// "Run" work with no internet. Responses keep their CORP/COEP headers, which
// the isolated runner page requires.
registerRoute(
  ({ url, sameOrigin }) =>
    sameOrigin && (url.pathname.startsWith("/toolchains/") || url.pathname.startsWith("/assets/")),
  new CacheFirst({
    cacheName: "notejs-code-runtimes",
    plugins: [new CacheableResponsePlugin({ statuses: [200] })],
  }),
);

// Activate new service worker immediately
self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// Turns an ISO date string (or Date) into milliseconds so two times can be compared.
const toMs = (value) => new Date(value).getTime();

// Listen for background sync events
self.addEventListener("sync", (event) => {
  if (event.tag.startsWith("sync-notes-")) {
    const userId = event.tag.replace("sync-notes-", "");
    event.waitUntil(syncNotesBackground(userId));
  }
});

async function syncNotesBackground(userId) {
  try {
    // 1. Fetch pending changes from IndexedDB, exactly as they were saved
    const localChanges = await localDB.notes
      .where("sync_status")
      .notEqual("synced")
      .and((note) => note.user_id === userId)
      .toArray();

    if (localChanges.length === 0) return;

    // Remember which version of each note we are sending (its real edit time)
    const sentVersions = new Map(
      localChanges.map((note) => [note.id, note.updated_at]),
    );

    // 2. Fetch lastSyncedAt from IndexedDB meta table
    const metaEntry = await localDB.meta.get(`lastSyncedAt_${userId}`);
    const lastSyncedAt = metaEntry ? metaEntry.value : null;

    // 3. Send batch request to the server using native fetch
    const res = await fetch("/api/notes/sync", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include", // Ensures HttpOnly cookies (JWT) are sent
      body: JSON.stringify({
        lastSyncedAt,
        localChanges,
      }),
    });

    if (!res.ok) {
      throw new Error(`Background sync failed with status: ${res.status}`);
    }

    const data = await res.json();
    const { serverChanges, timestamp } = data;

    // 4. Update IndexedDB with the results
    await localDB.transaction("rw", localDB.notes, localDB.meta, async () => {
      // Apply server changes, unless this device holds a newer unsent edit
      for (const serverNote of serverChanges ?? []) {
        const localNote = await localDB.notes.get(serverNote.id);

        const localHasNewerPendingEdit =
          localNote &&
          localNote.sync_status !== "synced" &&
          toMs(localNote.updated_at) > toMs(serverNote.updated_at);

        if (localHasNewerPendingEdit) continue;

        await localDB.notes.put({
          ...serverNote,
          sync_status: "synced",
        });
      }

      // Mark a note synced only if it is still the exact version we sent
      for (const [id, sentUpdatedAt] of sentVersions) {
        const current = await localDB.notes.get(id);

        if (
          current &&
          current.sync_status !== "synced" &&
          current.updated_at === sentUpdatedAt
        ) {
          await localDB.notes.update(id, { sync_status: "synced" });
        }
      }

      // Update sync timestamp
      await localDB.meta.put({
        key: `lastSyncedAt_${userId}`,
        value: timestamp,
      });
    });

    console.log("Service Worker: Background sync complete at", timestamp);
  } catch (error) {
    console.error("Service Worker: Sync Engine Failed:", error);
    // Rethrow to let the SyncManager know it failed, so it can retry later
    throw error;
  }
}
