import { precacheAndRoute } from 'workbox-precaching';
import { localDB } from '../lib/db.js';
import api from '../lib/axios.js';

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Activate new service worker immediately
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Listen for background sync events
self.addEventListener('sync', (event) => {
  if (event.tag.startsWith('sync-notes-')) {
    const userId = event.tag.replace('sync-notes-', '');
    event.waitUntil(syncNotesBackground(userId));
  }
});

async function syncNotesBackground(userId) {
  try {
    // 1. Fetch pending changes from IndexedDB
    const localChanges = await localDB.notes
      .where("sync_status")
      .notEqual("synced")
      .and((note) => note.user_id === userId)
      .toArray();

    if (localChanges.length === 0) return;

    // 2. Fetch lastSyncedAt from IndexedDB meta table
    const metaEntry = await localDB.meta.get(`lastSyncedAt_${userId}`);
    const lastSyncedAt = metaEntry ? metaEntry.value : null;

    // 3. Send batch request to the server
    const res = await api.post('/notes/sync', {
      lastSyncedAt,
      localChanges
    }, {
      adapter: 'fetch' // Ensure axios uses fetch adapter since XHR is unavailable in Service Workers
    });

    const data = res.data;
    const { serverChanges, timestamp } = data;

    // 4. Update IndexedDB with the results
    await localDB.transaction("rw", localDB.notes, localDB.meta, async () => {
      // Apply server changes
      if (serverChanges && serverChanges.length > 0) {
        for (const serverNote of serverChanges) {
          await localDB.notes.put({
            ...serverNote,
            sync_status: "synced",
          });
        }
      }

      // Mark local changes as synced
      if (localChanges.length > 0) {
        for (const localNote of localChanges) {
          await localDB.notes.update(localNote.id, { sync_status: "synced" });
        }
      }

      // Update sync timestamp
      await localDB.meta.put({ key: `lastSyncedAt_${userId}`, value: timestamp });
    });

    console.log("Service Worker: Background sync complete at", timestamp);
  } catch (error) {
    console.error("Service Worker: Sync Engine Failed:", error);
    // Rethrow to let the SyncManager know it failed, so it can retry later
    throw error;
  }
}
